<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Accepted filetype is .sql. Max Upload size allowed is 100M' => '',
    'All of the existing users including you, will be logged out once your restore is complete' => '',
    'Are you sure you want to delete this backup?' => '',
    'Are you sure you want to restore this backup?' => '',
    'Backup Job has been successfully deleted.' => '',
    'Backup Job has been successfully run.' => '',
    'Backup Job has been successfully updated.' => '',
    'Backup Jobs' => '',
    'Backup List' => '',
    'Backup Storage' => '',
    'Backup Storage ID' => '',
    'Backup Storage has been successfully created.' => '',
    'Backup Storage has been successfully deleted.' => '',
    'Backup Storage has been successfully updated.' => '',
    'Backup Storages' => '',
    'Backup file not found.' => '',
    'Backup generated successfully.' => '',
    'Backup in Progress' => '',
    'Backup job not found.' => '',
    'Backup successfully generated' => '',
    'Backup successfully removed' => '',
    'Backup uploaded successfully' => '',
    'Backups Jobs' => '',
    'Compression' => '',
    'Create Backup Job' => '',
    'Create Backup Storage' => '',
    'Database restored and migrations applied successfully.' => '',
    'Database restored, but migration failed.' => '',
    'Failed to clear database: {details}' => '',
    'Failed to delete Backup Job.' => '',
    'Failed to generate backup. Please try again.' => '',
    'Failed to generate the backup.' => '',
    'Failed to remove backup. Please try again.' => '',
    'Failed to remove the backup file.' => '',
    'Failed to run Backup Job.' => '',
    'Failed to save the backup to the list.' => '',
    'Failed to upload file' => '',
    'Filename' => '',
    'Generate Backup' => '',
    'Job ID' => '',
    'Keep Daily' => '',
    'Keep Hourly' => '',
    'Keep Last' => '',
    'Keep Monthly' => '',
    'Keep Weekly' => '',
    'Keep Yearly' => '',
    'Keep all backups' => '',
    'Mode' => '',
    'No available storage found.' => '',
    'No nodes found.' => '',
    'Please note that restoring from a backup will overwrite all existing data' => '',
    'Please wait while we generate a backup for you' => '',
    'Restoring from backup' => '',
    'Schedule' => '',
    'Select Backup Storage...' => '',
    'Selection Mode' => '',
    'Storage Ids' => '',
    'Success!' => '',
    'The Backup Feature is disabled because the backup storage is either full or unavailable.' => '',
    'The file already exists.' => '',
    'There was an error generating the backup.' => '',
    'Unknown error occurred.' => '',
    'Update Backup Job: ' => '',
    'Use the restore button' => '',
    'Virtual Data Center Backup Storage ID' => '',
    'Virtual Data Center Backup Storages' => '',
    'Yes, generate it!' => '',
    'You are about to generate a new backup.' => '',
    'to restore from a previous backup' => '',
];
