<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Catalogue' => '',
    'Choose the location for your Virtual Machine Template' => '',
    'Create VM Template' => '',
    'Create Virtual Machine Catalogue' => '',
    'Hardware Attachments' => '',
    'Import Templates from Proxmox to MultiPortal' => '',
    'Import VM Template from Proxmox' => '',
    'Import VM Templates' => '',
    'Importing. Please wait...' => '',
    'Information' => '',
    'Public' => '',
    'Select the VM Templates that you would like to sync from Proxmox to MultiPortal.<br><i>Note that only VM Templates that have not already been synced are shown.' => '',
    'Sync Wizard' => '',
    'The name you entered does not match the VM Template name.' => '',
    'The selected VM Template does not exist.' => '',
    'To confirm deletion, please type in the VM Template name:' => '',
    'Update Virtual Machine Catalogue: {name}' => '',
    'Upload' => '',
    'VM Template Import' => '',
    'VM Template imported successfully' => '',
    'VM Templates' => '',
    'Virtual Data Center...' => '',
    'Virtual Machine Catalogues' => '',
    'Virtual Machine Template' => '',
    'Virtual Machine Templates' => '',
    'Virtual Machines Template are required' => '',
];
