<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    ' days.' => '',
    ' to obtain a license key.' => '',
    '(Click here to go to the updater)' => '',
    'API Token' => '',
    'Active' => '',
    'Add License' => '',
    'Add License Key' => '',
    'Add a License Key' => '',
    'Allowed Sockets' => '',
    'Architecture' => '',
    'Available' => '',
    'Branding' => '',
    'Company Logo (Small) | Suggested Size: 146x146px' => '',
    'Company Logo | Suggested Size: 819x107px' => '',
    'Console Server Status' => '',
    'Current Socket Count' => '',
    'Current Version' => '',
    'Failed to update the license. Please try again later.' => '',
    'File Size Exceeded' => '',
    'Folder Writable' => '',
    'For more information please see:' => '',
    'Global Configurations' => '',
    'Host Name' => '',
    'How to Set your Public IP Address' => '',
    'Inactive' => '',
    'Infrastructure Settings' => '',
    'Invalid' => '',
    'Invalid File Type' => '',
    'Latest Version' => '',
    'License Status' => '',
    'License Type' => '',
    'License Updated' => '',
    'License key is required' => '',
    'License key setting not found. Please contact support.' => '',
    'License key was updated, but checking the license failed. Please contact support if this issue persists.' => '',
    'OFF' => '',
    'ON' => '',
    'OS Name' => '',
    'OS Version' => '',
    'Once you enter a valid license key, your instance will be permanently upgraded, and you will no longer be on a trial. ' => '',
    'Operating System' => '',
    'PHP Configuration Details' => '',
    'PHP Version' => '',
    'Percentage Used' => '',
    'Please add your Public IP address to your PHP config file or your .env file.' => '',
    'Please select JPEG, PNG, or GIF files only.' => '',
    'Public IP Address' => '',
    'Public IP Address Not Set' => '',
    'Registered Name' => '',
    'Registration Date' => '',
    'Service Status' => '',
    'Site Information' => '',
    'Site Name Not Set' => '',
    'System Info' => '',
    'System Overview' => '',
    'System Storage' => '',
    'System Uptime' => '',
    'The file size must not exceed 5 MB.' => '',
    'There is currently no valid license key assigned to this instance. Please click "Add License Key"' => '',
    'To continue using MultiPortal after your trial ends, visit ' => '',
    'Update License' => '',
    'Update your license key' => '',
    'Used' => '',
    'You are currently on a trial license.' => '',
    'Your trial will expire in ' => '',
];
