<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'API TOKEN' => '',
    'An error occurred while processing the command.' => '',
    'Console Dashboard' => '',
    'Console Logs' => '',
    'Errored' => '',
    'Failed to execute {action} command' => '',
    'Failed to retrieve PM2 status.' => '',
    'Launching' => '',
    'MultiPortal Console Server' => '',
    'Not Running' => '',
    'Note: The status and log output will refresh every 10 seconds.' => '',
    'Please run the following from ther terminal:' => '',
    'Restart' => '',
    'Stopped' => '',
    'The application encountered an error.' => '',
    'The application is launching.' => '',
    'The application is not running.' => '',
    'The application is running.' => '',
    'The application is stopped.' => '',
    'You can control your Console app/consolelication from this dashboard. If your console hasn\'t started, you can start it by clicking the Start button. If it\'s already running, you can stop or restart it.' => '',
    'Your MultiPortal instance does not have a token.' => '',
    'to generate one.' => '',
    '{action} Command executed successfully' => '',
];
