<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'An error has occurred, please try again. If the problem persists please contact your server provider.' => '',
    'An error occurred while processing your request. <br> Please contact us if you believe this is a server issue.' => '',
    'An error occurred while updating permissions.' => '',
    'Deleted VM' => '',
    'Download All Logs' => '',
    'Download Error Logs' => '',
    'Ended At' => '',
    'Error' => '',
    'Error ID: ' => '',
    'Error Logs' => '',
    'Error: No Storage Policy found' => '',
    'Error: {name} has no Proxmox storage assigned' => '',
    'Error: {storagePolicyName} has no Proxmox storage assigned for the Data Center selected ({dataCenterName})' => '',
    'Event' => '',
    'Failed to create internal network' => '',
    'Failed to save the file.' => '',
    'Incorrect username or password.' => '',
    'Internal server error occurred, please review the logs: ' => '',
    'Invalid file format!' => '',
    'Log' => '',
    'Reference ID' => '',
    'Show Logs' => '',
    'Started At' => '',
    'This {attribute} has already been taken.' => '',
    'Unknown Backup' => '',
    'Unknown VDC' => '',
    'Url' => '',
    'You are not allowed to perform this action.' => '',
    '{attribute} "{value}" has already been taken.' => '',
];
