<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Add a descriptive and easy-to-recognize name for this ISO file to simplify future identification.' => '',
    'Assign a friendly name to your ISO.' => '',
    'Atleast one ISO is required' => '',
    'Atleast one ISO name is required' => '',
    'Available on Proxmox' => '',
    'Check URL Metadata' => '',
    'Choose file' => '',
    'Choose how you want to upload your ISO file: directly from your computer or via a downloadable link.' => '',
    'Choose the VDC for your ISOs' => '',
    'Choose where to store your ISO and set its visibility for public or private access.' => '',
    'Configure ISO Storage and Accessibility' => '',
    'Confirm upload details' => '',
    'Data Center and Accessiblity' => '',
    'Edit Iso Storage' => '',
    'Enter friendly name' => '',
    'Failed to delete ISO. Please contact your Service Provider Administrator.' => '',
    'Failed to download ISO: {message} {errors}' => '',
    'Failed to save ISO Storage record' => '',
    'File Name (Auto-populated upon URL Check)' => '',
    'File URL' => '',
    'File Upload' => '',
    'Give Your ISO a Friendly Name' => '',
    'ISO Content is not found' => '',
    'ISO Content is not saved' => '',
    'ISO Deleted successfully' => '',
    'ISO File Upload Setup' => '',
    'ISO Import' => '',
    'ISO Name' => '',
    'ISO Name is Required' => '',
    'ISO Storage' => '',
    'ISO Storage is not set. Please contact your Service Provider Administrator.' => '',
    'ISO Storages' => '',
    'ISO Uploaded Succesfully' => '',
    'ISO Uploaded successfully' => '',
    'ISO name' => '',
    'ISO name is required' => '',
    'ISO name must be an array.' => '',
    'ISOs' => '',
    'ISOs Imported successfully' => '',
    'Import ISO from Proxmox' => '',
    'Import ISO from Proxmox to MultiPortal' => '',
    'Import ISOs' => '',
    'Invalid URL' => '',
    'Is Public' => '',
    'No ISO storage found for this data center.' => '',
    'No Storage available' => '',
    'No file chosen' => '',
    'No file selected' => '',
    'Note: Only ISOs that contain no spaces in the name, and have not already been imported are shown.' => '',
    'Please check the URL and try again.' => '',
    'Private ISOs' => '',
    'Private ISOs are kept isolated to the current VDC.' => '',
    'Public ISOs' => '',
    'Public ISOs are shared across all VDCs within the same Data Centre.' => '',
    'Select ISO Storage' => '',
    'Select ISO Upload Method' => '',
    'Select ISO drivers...' => '',
    'Select ISO...' => '',
    'Select the ISOs that you would like to sync from Proxmox to MultiPortal.' => '',
    'Storage is required' => '',
    'The filename must end with ".iso".' => '',
    'The value for ISO name \'{key}\' cannot be empty.' => '',
    'URL Verification Failed' => '',
    'Update ISO Storage: mode' => '',
    'Upload ISO' => '',
    'Upload Method' => '',
    'You do not have permission to delete this ISO.' => '',
];
