<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Grace period is active. Please update your license to resolve the socket mismatch issue. <br> You have <strong>{days}</strong> days left.' => '',
    'License Notification' => '',
    'No valid license is currently associated with your account. Please purchase a new license at {link}.' => '',
    'The license server is currently unreachable. Please try again later.' => '',
    'You are currently on a trial license. You have <strong>{trial_days_left}</strong> days remaining.' => '',
    'You are currently still on the Alpha or Beta license Key. This key will remain valid until the end of January 2025. You can obtain your own production license key from ' => '',
    'Your Community license grace period has ended due to a socket mismatch. Please update your license to continue using MultiPortal.' => '',
    'Your Community license has a socket mismatch. Your current license is valid for {socket} sockets, but you have {current_socket} sockets for your data center.<br> You have <strong>{grace_days_left}</strong> days remaining in the grace period to resolve this issue.' => '',
    'Your current license is valid for {socket} sockets, but you have {current_socket} sockets across your data centers. <br> To update your license, visit {link}.' => '',
    'Your grace period has ended. The socket mismatch issue must be resolved to continue using MultiPortal.' => '',
    'Your license is invalid, expired, or suspended. To renew your license, visit {link}.' => '',
    'Your trial has ended. Please purchase a license to continue using MultiPortal.' => '',
    'Your trial subscription has expired. You have <strong>{days}</strong> days remaining as a grace period to renew your license.' => '',
    'expired' => '',
    'invalid' => '',
    'license_valid' => '',
    'suspended' => '',
];
