<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '<i class="mdi mdi-network"> </i> Create Internal Network' => '',
    '<i class="mdi mdi-network"> </i> Create a new network' => '',
    'A list of IP addresses of each node in the VXLAN zone. This can be external nodes reachable at this IP address. All nodes in the cluster need to be mentioned here.' => '',
    'Alias' => '',
    'Assigned to' => '',
    'Attached Virtual Machines: ' => '',
    'Basic configuration for your external network' => '',
    'Bridge' => '',
    'Create Data Center Vnet' => '',
    'Create External Network' => '',
    'Create Internal Network' => '',
    'Create New Network' => '',
    'Create New Zone' => '',
    'Create VNET' => '',
    'Do you want to create new vnet or use existing one within the zone?' => '',
    'Do you want to create new zone or use existing one?' => '',
    'Edit Accessibility' => '',
    'Edit: ' => '',
    'Edit: mode' => '',
    'External Network Configuration' => '',
    'External Networks' => '',
    'External networks are mapped to an underlying VLAN within Proxmox.' => '',
    'Failed to update network mode' => '',
    'Gateway' => '',
    'General Configuration' => '',
    'If a new zone is selected, a new VNet must also be created. The Zone ID will follow MultiPortal naming convention (e.g., "E0000001"' => '',
    'If the selected bridge is not available in the node of Virtual Machine, the network will not be listed as an option. To avoid this, please make sure the bridge is available in all nodes of the data center. This cannot be updated once created.' => '',
    'Internal Networks' => '',
    'Invalid Virtual Data Center ID.' => '',
    'Ipam' => '',
    'MTU' => '',
    'Name is Required' => '',
    'Network' => '',
    'Network Configuration' => '',
    'Network ID' => '',
    'Network mode' => '',
    'Networking' => '',
    'Networks' => '',
    'New Network' => '',
    'Not Set' => '',
    'Owner' => '',
    'Peer Address List' => '',
    'SDN - Zones' => '',
    'Search Network by Name, Network ID or Tag' => '',
    'Select Bridge...' => '',
    'Select IPAM...' => '',
    'Select Type...' => '',
    'Select VNet...' => '',
    'Select Zone...' => '',
    'Select a Tenant ...' => '',
    'Select a VDC ...' => '',
    'Select a bridge...' => '',
    'Select a tenant...' => '',
    'Select what VDCs you want to have access to your external network' => '',
    'Select which VNet you want to use for your external network' => '',
    'Subnet' => '',
    'Tag' => '',
    'Tag {tag} is already in use. Please input another tag.' => '',
    'Tag {tag} is reserved. Please input another tag.' => '',
    'The VNet ID will follow MultiPortal naming convention (e.g., "VL000001")' => '',
    'The name you entered does not match the network name.' => '',
    'This network is attached to a virtual machine and cannot be deleted.' => '',
    'To confirm deletion, please type in the network name:' => '',
    'Update Accessibility' => '',
    'Update Data Center Vnet: {name}' => '',
    'Update: ' => '',
    'VLAN' => '',
    'VLAN must be between 1 and 4094.' => '',
    'VNET' => '',
    'VNet' => '',
    'VNet Configuration' => '',
    'VNet is Required' => '',
    'View VMs' => '',
    'View VNet Map' => '',
    'Zone' => '',
    'Zone Configuration' => '',
    'Zone ID' => '',
    'Zone Type' => '',
    'Zone is Required' => '',
    'Zone: ' => '',
    'created successfully.' => '',
    'deleted successfully.' => '',
    'e.g. 192.168.0.0/24 - Note that this is informational only.' => '',
    'e.g. 192.168.0.254 - Note that this is informational only.' => '',
];
