<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'API Client "mode' => '',
    'API Clients' => '',
    'Accepted filetype is .sql. Max Upload size allowed is 20M' => '',
    'Child ID' => '',
    'Client ID' => '',
    'Client Secret' => '',
    'Create API Client' => '',
    'Data Type' => '',
    'Error deleting API Client "mode' => '',
    'Extended Trial' => '',
    'Extended Trial Start Date' => '',
    'Failed to create role.' => '',
    'Failed to delete role.' => '',
    'Failed to delete user.' => '',
    'Failed to update role.' => '',
    'Google Client ID' => '',
    'Google Client Secret' => '',
    'Google Redirect URI' => '',
    'Google SSO Configuration' => '',
    'Google SSO Enabled' => '',
    'Initial Trial' => '',
    'Initial Trial Start Date' => '',
    'License Information' => '',
    'License Key' => '',
    'License Key (Optional)' => '',
    'Localkey' => '',
    'Maintenance mode is enabled. Disable maintenance mode to continue.' => '',
    'Microsoft Client ID' => '',
    'Microsoft Client Secret' => '',
    'Microsoft Redirect URI' => '',
    'Microsoft SSO Configuration' => '',
    'Microsoft SSO Enabled' => '',
    'No link found for {source}' => '',
    'Parent ID' => '',
    'Please check back in sometime' => '',
    'Product Name' => '',
    'Redirect URI' => '',
    'Role created successfully.' => '',
    'Role deleted successfully.' => '',
    'Role does not exist.' => '',
    'Role updated successfully.' => '',
    'SSO Configuration' => '',
    'SSO Configuration Saved!' => '',
    'Save Google Configuration' => '',
    'Save Microsoft Configuration' => '',
    'Settings Saved!' => '',
    'Site is Under Maintenance' => '',
    'Successfully unlinked {source}' => '',
    'The value must be a boolean (0 or 1).' => '',
    'The value must be a string.' => '',
    'The value must be an integer.' => '',
    'The value must be an number.' => '',
    'This feature is not available in the Community version.' => '',
    'Upload Backup' => '',
    'User Successfully Deleted.' => '',
    'User Successfully Updated.' => '',
];
