<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'A new version of MultiPortal is available. Update to ' => '',
    'As part of the update, your database will be backed up to ensure that no data is lost during the process. This' => '',
    'Completed' => '',
    'Confirm Upgrade' => '',
    'Could not complete the upgrade. Please check your network connection and try again.' => '',
    'Current Release' => '',
    'During the update, your application will be updated to the new version, it will update any necessary libraries and dependencies.' => '',
    'MultiPortal Release Notes' => '',
    'MultiPortal Update' => '',
    'MultiPortal Updater' => '',
    'Network Error!' => '',
    'Please do not close this window.' => '',
    'The updater is designed to ensure a smooth transition between versions and will perform a few important tasks' => '',
    'There was an issue during the upgrade process. Please try again later.' => '',
    'UPGRADE' => '',
    'Unable to proceed with Update!' => '',
    'Upgrade Completed Successfully!' => '',
    'Upgrade Failed!' => '',
    'Upgrade in progress, please wait...' => '',
    'Upgrade to the latest version of MultiPortal.' => '',
    'We will be stopping the Console server during the update to ensure that the update process is smooth.' => '',
    'Welcome to the MultiPortal Update! This process will update your MultiPortal application to the latest version.' => '',
    'You already have the latest version of MultiPortal installed!' => '',
    'You are running the latest version of MultiPortal.' => '',
    'automatically.' => '',
    'safeguard helps protect your system in case any issues arise during the update.' => '',
];
